# Name of this workflow
name: Continuous

# Configure action events that trigger this workflow
on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**.md'

# Configure jobs this workflow consists of
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout Workspace
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Build
        run: mvn -B -e -V -T1 install -DskipTests=true

      - name: Unit Test
        run: mvn -B -e -V -T1 surefire:test

      - name: Integration Test
        run: mvn -B -e -V -T1 failsafe:integration-test
      
